export const stages = [
  {
    title: "行业认知",
    en: "UNDERSTAND THE PRODUCT",
    days: "Day 01–03",
    skill: "产品与产业链分析",
    goal: "看懂一个产品，以及谁会买它。",
    lessons: [
      "汽车刹车片海外获客基础",
      "拆解产品参数与应用场景",
      "绘制制造业采购链",
    ],
    body: [
      "先区分原厂配套（OEM）与售后市场（Aftermarket）：前者面向整车厂及其供应链，后者服务车辆维修与零部件更换。两者的客户、验证周期与采购方式不同。",
      "以刹车片为例，常见链路是：中国制造商 → 海外进口商 / 经销商 → 批发商 → 汽配店 / 修理厂 → 车主。角色可能重叠，不要只凭公司名称判断。",
      "采购比较的是适配车型、质量一致性、交期、售后与总成本。低价不是唯一理由；缺货、产品线扩充、现有供货不稳定都可能触发更换供应商。",
    ],
    exercise: "选一种制造业产品，写清用途、采购角色、三个采购关注点和供应链。",
  },
  {
    title: "客户画像 ICP",
    en: "DEFINE YOUR CUSTOMER",
    days: "Day 04–06",
    skill: "客户画像构建",
    goal: "把“海外客户”变成可验证的筛选条件。",
    lessons: ["定义理想客户画像", "区分必选条件与加分信号", "验证画像假设"],
    body: [
      "ICP 是理想客户画像。先写地区、行业、业务角色、销售产品、规模和采购模式，再写联系人职位。",
      "刹车片练习画像：墨西哥售后汽配进口商或经销商，明确经营制动产品，有批发业务或仓储能力。10–200 人只是练习范围，不是硬性标准。",
      "把“寻找中国供应商”标记为待验证假设。经营亚洲车型配件不等于从中国采购；全球采购、自有品牌也只是线索。",
    ],
    exercise:
      "为一家工业泵工厂写一个 ICP，列出 3 个必选条件、2 个加分信号和 2 个排除条件。",
  },
  {
    title: "潜客判断",
    en: "QUALIFY WITH EVIDENCE",
    days: "Day 07–09",
    skill: "潜客证据与分级",
    goal: "先判断是否值得开发，再找邮箱。",
    lessons: ["阅读企业网站", "A / B / C 客户分级", "建立证据与待核实清单"],
    body: [
      "依次检查产品相关性、制动产品、商业角色、采购能力以及供应链线索。每项判断要保留网页地址、原文摘要与核实日期。",
      "A 类：产品、采购角色和采购能力都有明确证据。B 类：方向相关但缺少关键证据。C 类：明显不匹配当前批量开发目标。",
      "公司经营多年、仓库或 SKU 数量只是信号，不能自动证明采购意向。区分已确认事实与推测，避免把低证据企业直接列为 A 类。",
    ],
    exercise: "分析 5 家企业，每家填写分级、证据、联系人职位和下一步核实动作。",
  },
  {
    title: "外贸基础",
    en: "LEARN THE TRADE",
    days: "Day 10–12",
    skill: "询盘与报价要素",
    goal: "把询盘转成双方都理解的交易条件。",
    lessons: ["询盘与样品流程", "MOQ、交期与付款", "报价边界与交付条件"],
    body: [
      "询价先确认产品型号、数量、包装、目的地和用途。样品验证、批量采购与长期协议分别处理。",
      "报价应注明币种、有效期、最低起订量、交期、付款安排和交付地点，明确包含与不包含的费用。",
      "贸易术语、进口要求和认证需按目标市场与实际交易核实。本平台只训练问题清单，不能替代正式合同或合规审查。",
    ],
    exercise:
      "制作一份询价信息清单，并写出信息不足时需要向买家确认的 5 个问题。",
  },
  {
    title: "商务英语",
    en: "WRITE WITH CLARITY",
    days: "Day 13–15",
    skill: "英文开发信写作",
    goal: "用简短、具体的英文推进下一步。",
    lessons: ["10 个外贸高频词", "首封开发信", "跟进与澄清问题"],
    body: [
      "每封开发信只做一件事：提出与对方业务相关的合作假设，并给出轻量的下一步。避免堆砌公司介绍。",
      "用证据开头：I noticed your catalog includes brake components. 然后说明你能提供什么，并提出一个容易回答的问题。",
      "不要虚构认证、客户或供应能力。跟进补充新信息，尊重对方不再联系的要求。",
    ],
    exercise:
      "写一封不超过 100 个英文词的邮件，包含业务关联、价值主张和一个问题。",
  },
  {
    title: "销售沟通",
    en: "DISCOVER THE NEED",
    days: "Day 16–18",
    skill: "需求访谈与异议处理",
    goal: "理解采购动机，而不是急着推销。",
    lessons: ["采购需求访谈", "处理价格与信任异议", "设计下一步承诺"],
    body: [
      "用开放问题确认现状：哪些型号经常缺货？当前供应商哪里需要改善？你们怎样评估新供应商？",
      "遇到“太贵”，先澄清比较的是单价、落地成本还是质量风险。遇到“已有供应商”，可以讨论补充型号或备选供应。",
      "每次交流约定一个明确动作、负责人和时间，例如提供两款产品资料并在周五确认是否安排样品。",
    ],
    exercise: "写出 5 个需求访谈问题，并给“我们已有供应商”准备一段回复。",
  },
  {
    title: "客户开发",
    en: "BUILD YOUR PIPELINE",
    days: "Day 19–23",
    skill: "开发计划与跟进",
    goal: "建立可以复盘的客户开发流程。",
    lessons: ["设计搜索与证据记录", "准备触达材料", "建立跟进节奏"],
    body: [
      "搜索从产品词 + 商业角色 + 地区开始。把企业官网、目录与公开企业资料交叉核对，不把搜索摘要当作结论。",
      "记录公司、产品匹配证据、分级、联系人角色、联系方式来源和下一步。先用少量高匹配样本验证策略。",
      "AI 可以整理和起草，不能凭空补齐联系人、邮箱或采购意向。触达前人工核对信息与适用要求。",
    ],
    exercise:
      "设计一个 7 天开发计划：目标客户数量、筛选条件、首封邮件和两次跟进各提供什么新信息。",
  },
  {
    title: "项目交付",
    en: "DELIVER THE WORK",
    days: "Day 24–28",
    skill: "项目交付与复盘",
    goal: "把研究过程变成客户能使用的成果。",
    lessons: ["定义项目范围", "交付名单与开发方案", "复盘与报价"],
    body: [
      "先明确交付边界：提供研究名单、联系人核实还是代运营？不要把“潜在客户名单”承诺成“成交客户”。",
      "交付应包含产品分析、ICP、带证据的客户清单、分级、沟通策略和待验证风险。让别人能够复查你的判断。",
      "服务报价可按工作项、工时和验收标准组织。把你的服务费与制造企业的产品报价分开。",
    ],
    exercise:
      "为工业泵出海研究项目写一页交付方案，说明范围、时间、验收标准与服务报价。",
  },
];
export const terms = [
  ["Brake Pad", "刹车片"],
  ["Manufacturer", "制造商"],
  ["Importer", "进口商"],
  ["Distributor", "经销商"],
  ["Wholesaler", "批发商"],
  ["Aftermarket", "汽车售后市场"],
  ["OEM", "原厂配套"],
  ["MOQ", "最低起订量"],
  ["Private Label", "客户自有品牌代工"],
  ["Purchasing Manager", "采购经理"],
];
export const tasks = [
  {
    id: "product",
    title: "读懂刹车片与采购链",
    time: "20 分钟",
    hint: "完成 Day 1 产品认知，回答产品卖给谁。",
  },
  {
    id: "terms",
    title: "学习 10 个外贸高频词",
    time: "25 分钟",
    hint: "用自己的话解释 Importer、Aftermarket 和 MOQ。",
  },
  {
    id: "icp",
    title: "写出你的第一份客户画像",
    time: "30 分钟",
    hint: "完成课程中的墨西哥汽配 ICP 练习。",
  },
  {
    id: "cases",
    title: "判断 5 家海外汽配企业",
    time: "30 分钟",
    hint: "在案例训练中提交 5 家模拟企业的判断。",
  },
  {
    id: "review",
    title: "记录今日收获与疑问",
    time: "15 分钟",
    hint: "在下方学习记录里留下一个收获和一个待解决问题。",
  },
];
export const dailyLessons = [
  {
    day: 1,
    stage: "行业认知",
    title: "汽车刹车片海外获客基础",
    duration: "约 2 小时",
    objective: "看懂一个产品，以及谁会买它。",
    concepts: [
      "区分 OEM 原厂配套与 Aftermarket 售后市场",
      "画出制造商、进口商、经销商、修理厂之间的采购链",
      "认识 10 个外贸高频词，并完成第一份墨西哥汽配 ICP",
    ],
    practice:
      "用 5 句话说明刹车片卖给谁、买家关心什么，以及为什么会更换供应商。",
    deliverable: "一份刹车片采购链笔记 + 第一版 ICP",
  },
  {
    day: 2,
    stage: "行业认知",
    title: "把产品说明书翻译成买家语言",
    duration: "90 分钟",
    objective: "从参数中找出真正影响采购的卖点。",
    concepts: [
      "把材料、规格、适配范围分成事实与优势",
      "用“参数—使用场景—买家收益”三列改写产品信息",
      "标记认证、产能和交期等仍需工厂确认的内容",
    ],
    practice: "选一种制造业产品，将 5 个参数改写成买家能理解的价值表达。",
    deliverable: "产品价值翻译表",
  },
  {
    day: 3,
    stage: "行业认知",
    title: "绘制制造业采购地图",
    duration: "90 分钟",
    objective: "理解不同采购角色的利益与决策权。",
    concepts: [
      "识别进口商、分销商、批发商、代理商与终端工厂",
      "区分使用者、影响者、审批者和最终采购人",
      "为每个角色记录关注点和常见风险",
    ],
    practice: "为一个工业品画出从中国工厂到海外终端的完整采购路径。",
    deliverable: "一张采购角色地图",
  },
  {
    day: 4,
    stage: "客户画像 ICP",
    title: "从“海外企业”缩小到可搜索客户",
    duration: "100 分钟",
    objective: "把模糊目标转成可执行的筛选条件。",
    concepts: [
      "定义地区、行业、商业角色、产品与规模",
      "区分必选条件、加分信号和排除条件",
      "将“可能需要”标为假设，而不是事实",
    ],
    practice: "为工业泵进入墨西哥市场写出第一版 ICP。",
    deliverable: "一页 ICP 卡片",
  },
  {
    day: 5,
    stage: "客户画像 ICP",
    title: "用反向画像排除低价值线索",
    duration: "75 分钟",
    objective: "减少把时间浪费在不合适企业上。",
    concepts: [
      "识别终端小店、无关批发商和纯服务企业",
      "判断小规模客户何时仍值得保留",
      "为每条排除条件写出证据标准",
    ],
    practice: "给 10 条模拟线索做保留、待核实或排除判断。",
    deliverable: "客户排除清单",
  },
  {
    day: 6,
    stage: "客户画像 ICP",
    title: "验证客户画像，而不是相信猜测",
    duration: "90 分钟",
    objective: "用少量真实样本修正 ICP。",
    concepts: [
      "先用 5–10 家样本测试搜索条件",
      "记录哪些条件过宽、过窄或无法验证",
      "保留画像版本与修改理由",
    ],
    practice: "用 5 家企业样本检查 Day 4 的 ICP，并修改至少一项条件。",
    deliverable: "ICP v2 与修改记录",
  },
  {
    day: 7,
    stage: "潜客判断",
    title: "快速读懂一家海外公司网站",
    duration: "90 分钟",
    objective: "在 10 分钟内找到客户判断需要的证据。",
    concepts: [
      "优先查看产品、关于我们、品牌、网络与联系页面",
      "区分企业自述、第三方信息和搜索摘要",
      "记录原文、页面地址和核实日期",
    ],
    practice: "选择一家企业，完成网站证据速读卡。",
    deliverable: "企业证据卡",
  },
  {
    day: 8,
    stage: "潜客判断",
    title: "建立 A / B / C 分级规则",
    duration: "90 分钟",
    objective: "让不同企业的优先级可比较。",
    concepts: [
      "A 类需要产品、角色和采购能力的明确证据",
      "B 类保留相关但缺少关键证据的企业",
      "C 类记录不匹配原因，避免重复研究",
    ],
    practice: "完成平台中的 5 家模拟企业判断并查看反馈。",
    deliverable: "5 家企业分级表",
  },
  {
    day: 9,
    stage: "潜客判断",
    title: "把判断变成下一步行动",
    duration: "75 分钟",
    objective: "为每个等级设计不同的核实方式。",
    concepts: [
      "A 类准备个性化触达与产品资料",
      "B 类先核实产品线或采购角色",
      "C 类停止开发或仅作市场观察",
    ],
    practice: "为 A、B、C 各写一条下一步行动。",
    deliverable: "分级行动清单",
  },
  {
    day: 10,
    stage: "外贸基础",
    title: "读懂询盘并补齐缺失信息",
    duration: "90 分钟",
    objective: "把模糊询价转成可报价需求。",
    concepts: [
      "确认型号、数量、用途、包装和目的地",
      "区分样品、试单与长期采购",
      "用问题清单减少错误报价",
    ],
    practice: "为一封只有“Please send price”的询盘写 6 个澄清问题。",
    deliverable: "询盘核对表",
  },
  {
    day: 11,
    stage: "外贸基础",
    title: "MOQ、交期与付款条件",
    duration: "90 分钟",
    objective: "理解常见交易条件之间的关系。",
    concepts: [
      "MOQ 与生产、包装和运输成本相关",
      "交期从资料确认和付款条件满足后计算",
      "付款方式影响双方风险与现金流",
    ],
    practice: "比较样品单、试单和批量单的条件差异。",
    deliverable: "三种订单条件对比表",
  },
  {
    day: 12,
    stage: "外贸基础",
    title: "写一份边界清楚的报价",
    duration: "100 分钟",
    objective: "让买家清楚价格包含什么。",
    concepts: [
      "注明币种、有效期、数量阶梯和交期",
      "明确包装、运费、税费和目的地边界",
      "把待确认项写入备注，不做口头假设",
    ],
    practice: "根据模拟询盘制作一页报价框架。",
    deliverable: "报价单草稿",
  },
  {
    day: 13,
    stage: "商务英语",
    title: "建立你的外贸表达词库",
    duration: "70 分钟",
    objective: "掌握能直接用于客户开发的基本表达。",
    concepts: [
      "按产品、公司角色、采购和物流整理词汇",
      "用完整业务句理解词义",
      "保留自己容易混淆的词和例句",
    ],
    practice: "从知识库选 15 个词，各写一个与业务相关的短句。",
    deliverable: "个人外贸词库",
  },
  {
    day: 14,
    stage: "商务英语",
    title: "写一封具体的首封开发信",
    duration: "90 分钟",
    objective: "在 100 个英文词内说明相关性与下一步。",
    concepts: [
      "用对方产品或市场证据开头",
      "只表达一个可验证的价值主张",
      "结尾提出一个容易回答的问题",
    ],
    practice: "为一名墨西哥汽配采购经理写首封邮件。",
    deliverable: "首封开发信 v1",
  },
  {
    day: 15,
    stage: "商务英语",
    title: "跟进邮件与澄清问题",
    duration: "80 分钟",
    objective: "用新信息推进对话。",
    concepts: [
      "每次跟进补充规格、案例或问题",
      "避免只写“Did you see my email”",
      "尊重拒绝、退订和不再联系要求",
    ],
    practice: "为 Day 14 邮件写两次内容不同的跟进。",
    deliverable: "两封跟进邮件",
  },
  {
    day: 16,
    stage: "销售沟通",
    title: "用问题发现真实采购需求",
    duration: "90 分钟",
    objective: "理解买家为什么现在可能需要改变。",
    concepts: [
      "询问现状、困难、影响和评估标准",
      "先理解需求，再介绍产品",
      "区分明确需求、潜在需求和无需求",
    ],
    practice: "写出 8 个适用于工业品采购访谈的问题。",
    deliverable: "需求访谈提纲",
  },
  {
    day: 17,
    stage: "销售沟通",
    title: "处理价格与信任异议",
    duration: "90 分钟",
    objective: "从异议中找出买家的真实顾虑。",
    concepts: [
      "先澄清比较口径，再解释价格",
      "用证据降低质量、交付和售后风险",
      "不贬低竞争对手，不虚构客户案例",
    ],
    practice: "分别回应“价格太高”和“我们已有供应商”。",
    deliverable: "异议回应卡",
  },
  {
    day: 18,
    stage: "销售沟通",
    title: "把沟通落到明确下一步",
    duration: "75 分钟",
    objective: "结束每次交流时形成可执行承诺。",
    concepts: [
      "约定动作、负责人和时间",
      "把大承诺拆成资料、样品或会议等小步骤",
      "会后用书面内容确认一致理解",
    ],
    practice: "将三个模糊结束语改写成明确下一步。",
    deliverable: "下一步行动模板",
  },
  {
    day: 19,
    stage: "客户开发",
    title: "设计高质量潜客搜索式",
    duration: "90 分钟",
    objective: "用产品、角色和地区组合找到相关企业。",
    concepts: [
      "组合产品同义词、商业角色词和地区词",
      "搜索企业官网、行业目录与展会名录",
      "不要把搜索摘要直接当成证据",
    ],
    practice: "为工业泵墨西哥市场写 8 条不同搜索式。",
    deliverable: "搜索词组合表",
  },
  {
    day: 20,
    stage: "客户开发",
    title: "建立带证据的潜客名单",
    duration: "110 分钟",
    objective: "让名单中的每个判断都能复查。",
    concepts: [
      "记录公司、网址、匹配证据和核实日期",
      "联系人职位与联系方式分开核实",
      "不猜测邮箱、不填充虚构信息",
    ],
    practice: "建立 5 家潜客的小样本名单。",
    deliverable: "5 家潜客证据表",
  },
  {
    day: 21,
    stage: "客户开发",
    title: "找到正确的采购角色",
    duration: "80 分钟",
    objective: "判断应联系采购、老板还是业务负责人。",
    concepts: [
      "公司规模会影响职位设置",
      "产品采购与战略合作可能由不同角色负责",
      "公开联系方式也要核实来源和用途",
    ],
    practice: "为 5 家潜客分别选择首选和备选职位。",
    deliverable: "联系人角色地图",
  },
  {
    day: 22,
    stage: "客户开发",
    title: "准备个性化触达材料",
    duration: "100 分钟",
    objective: "把公司证据与产品价值连起来。",
    concepts: [
      "每封邮件引用一条可核实的相关信息",
      "按客户产品线选择资料，不发送大而全附件",
      "记录使用的模板版本和假设",
    ],
    practice: "为 3 家不同等级客户各写一条个性化开场。",
    deliverable: "三条个性化开发信息",
  },
  {
    day: 23,
    stage: "客户开发",
    title: "建立可复盘的 7 天开发节奏",
    duration: "90 分钟",
    objective: "把搜索、触达与跟进连成流程。",
    concepts: [
      "设定每天可完成的研究和触达数量",
      "为两次跟进准备不同价值信息",
      "记录回复、拒绝、退信和待跟进状态",
    ],
    practice: "制定一份 7 天开发日历与衡量指标。",
    deliverable: "7 天客户开发计划",
  },
  {
    day: 24,
    stage: "项目交付",
    title: "定义项目范围与验收标准",
    duration: "90 分钟",
    objective: "让制造企业知道会得到什么结果。",
    concepts: [
      "区分研究名单、联系人核实和代运营",
      "把交付数量、字段、时间和质量写清楚",
      "潜客名单不等于询盘或成交承诺",
    ],
    practice: "为 2 周海外获客研究项目写范围说明。",
    deliverable: "项目范围说明书",
  },
  {
    day: 25,
    stage: "项目交付",
    title: "整理客户名单与判断证据",
    duration: "100 分钟",
    objective: "把研究结果变成客户可使用的成果。",
    concepts: [
      "统一字段、分级口径和证据格式",
      "区分事实、推测与待验证项",
      "加入下一步建议而不夸大确定性",
    ],
    practice: "把 5 家潜客整理成可交付版本。",
    deliverable: "潜客名单 v1",
  },
  {
    day: 26,
    stage: "项目交付",
    title: "制作开发策略与沟通材料",
    duration: "100 分钟",
    objective: "让名单能够直接进入开发阶段。",
    concepts: [
      "按 A / B / C 设计不同动作",
      "为重点客户准备邮件与问题清单",
      "注明资料使用限制和人工核实要求",
    ],
    practice: "完成一个重点客户的完整开发包。",
    deliverable: "重点客户开发包",
  },
  {
    day: 27,
    stage: "项目交付",
    title: "设计服务报价与风险边界",
    duration: "90 分钟",
    objective: "把工作量、价值和责任写进报价。",
    concepts: [
      "按工作项、工时或成果组合计价",
      "明确修改轮次、验收和付款节点",
      "将服务费与产品报价、广告费分开",
    ],
    practice: "为两周研究项目写一份服务报价。",
    deliverable: "服务报价方案",
  },
  {
    day: 28,
    stage: "项目交付",
    title: "完成第一次模拟项目复盘",
    duration: "120 分钟",
    objective: "把 28 天能力汇总成可展示的作品。",
    concepts: [
      "检查产品分析、ICP、名单、分级和策略是否一致",
      "记录最容易误判的环节和改进动作",
      "导出方案并形成下一阶段学习目标",
    ],
    practice: "在模拟接单区完成并导出一个六步项目。",
    deliverable: "第一份海外获客项目作品集",
  },
];

export const makeDayTasks = (day: number) => {
  const lesson =
    dailyLessons[Math.max(0, Math.min(dailyLessons.length - 1, day - 1))];
  return [
    {
      id: "learn",
      title: `学习：${lesson.title}`,
      time: "25 分钟",
      hint: `理解今天的目标：${lesson.objective}`,
    },
    {
      id: "notes",
      title: "整理三个核心知识点",
      time: "20 分钟",
      hint: lesson.concepts.join("；"),
    },
    {
      id: "practice",
      title: "完成今日练习",
      time: "30 分钟",
      hint: lesson.practice,
    },
    {
      id: "deliver",
      title: "产出今日成果",
      time: "25 分钟",
      hint: `交付物：${lesson.deliverable}`,
    },
    {
      id: "review",
      title: "记录收获与疑问",
      time: "10 分钟",
      hint: "写下一个今天学会的判断方法和一个仍需验证的问题。",
    },
  ];
};
export const cases = [
  {
    id: "mx01",
    name: "Atlas Auto Distribución",
    country: "墨西哥 · 瓜达拉哈拉",
    type: "进口商 / 经销商",
    grade: "A",
    position: "采购经理",
    facts: [
      "面向汽配零售商经营售后配件批发。",
      "目录明确包含 brake pads、brake discs。",
      "拥有两个仓库，开展进口及自有品牌业务。",
    ],
    reason:
      "产品、B2B 角色、仓储与进口能力均有证据，符合刹车片工厂的批量客户画像。实际需求与资质仍需核实。",
    strategy:
      "联系采购经理，先确认车型覆盖、月度补货与自有品牌要求，再提供匹配型号资料和样品建议。",
  },
  {
    id: "mx02",
    name: "Ruta Parts Supply",
    country: "墨西哥 · 蒙特雷",
    type: "批发商",
    grade: "B",
    position: "采购经理",
    facts: [
      "向本地汽配店批发滤清器、皮带和润滑油。",
      "网站未展示制动产品。",
      "有配送团队，但采购来源未披露。",
    ],
    reason:
      "具备相关渠道，但缺少刹车片产品与采购模式证据，宜先核实而非直接报价。",
    strategy: "询问是否计划扩展制动产品线，确认采购负责人与供应商评估流程。",
  },
  {
    id: "ae01",
    name: "Gulf Brake Trading",
    country: "阿联酋 · 迪拜",
    type: "进口商 / 经销商",
    grade: "A",
    position: "采购经理",
    facts: [
      "向区域经销商批量供应刹车片与刹车盘。",
      "提供自有品牌包装，并披露进口业务。",
      "拥有仓库及批量询价入口。",
    ],
    reason:
      "针对“地区不限的售后刹车片批量客户”画像，产品与渠道高度匹配。若 ICP 限定墨西哥，则应排除或移入其他市场名单。",
    strategy:
      "核实销售目的国、车型和包装需求，提供可验证的产品资料；进口要求按具体市场另行核实。",
  },
  {
    id: "us01",
    name: "Oak Street Garage",
    country: "美国 · 奥斯汀",
    type: "修理厂 / 零售商",
    grade: "C",
    position: "老板 / 总经理",
    facts: [
      "单店经营维修、保养与刹车片更换。",
      "配件从本地批发商按需采购。",
      "没有批发、进口或集中采购业务。",
    ],
    reason:
      "有使用需求，但不匹配当前跨境批量获客目标。C 类表示本轮低优先级，并非没有商业价值。",
    strategy:
      "本轮不优先开发；如需了解终端需求，可研究其服务范围，但不要把它当作进口买家。",
  },
  {
    id: "de01",
    name: "Nord Werkzeug Handel",
    country: "德国 · 汉堡",
    type: "无关行业",
    grade: "C",
    position: "不适用",
    facts: [
      "主营木工工具及家用五金。",
      "没有汽车配件或制动产品。",
      "客户为五金零售商。",
    ],
    reason: "行业和产品均不匹配，即使存在批发能力也不属于刹车片目标客户。",
    strategy: "从本轮客户名单中排除，记录不匹配原因，避免重复研究。",
  },
];
export const knowledge = [
  {
    category: "外贸术语",
    title: "10 个入门词：从产品到采购角色",
    text:
      terms.map((t) => t.join(" · ")).join("\n") +
      "\n\n例句：We are looking for aftermarket brake pad distributors.\n我们正在寻找汽车售后刹车片经销商。",
  },
  {
    category: "行业知识",
    title: "刹车片：先理解采购链",
    text: "中国制造商 → 进口商 / 经销商 → 批发商 → 汽配店 / 修理厂 → 车主。\n\nOEM 面向整车配套；Aftermarket 面向维修替换。产品适配、质量一致性、供货稳定、售后和总成本都影响采购。\n\n不要仅凭“经营亚洲车型”推断其从中国采购。",
  },
  {
    category: "邮件案例",
    title: "首封开发信：从对方目录切入",
    text: "Subject: Brake pad range for your aftermarket catalog\n\nHi [Name],\nI noticed your catalog includes brake components for [vehicle segment]. We manufacture [verified product range] and can share specifications for your review.\nAre you currently evaluating additional suppliers for this range?\n\nBest regards,\n[Your name]\n\n使用前替换方括号，并核实目录与供应能力。这是练习模板，不代表已获得联系许可。",
  },
  {
    category: "客户画像",
    title: "墨西哥售后汽配经销商 ICP",
    text: "地区：墨西哥\n角色：汽配进口商 / 经销商\n产品：刹车片、刹车盘或刹车蹄\n渠道：服务汽配店或批发网络\n规模：10–200 人作为练习参考，不能仅凭规模排除\n职位：采购经理、老板或总经理\n待验证：进口能力、采购周期、自有品牌需求。",
  },
  {
    category: "异议处理",
    title: "“我们已经有供应商了”",
    text: "先承认现状，再了解补充机会。\n\nThanks for letting me know. Do you ever evaluate backup suppliers for stock shortages or new product ranges?\n\n不要贬低原供应商，也不要立刻降价。如果明确拒绝，尊重对方选择。",
  },
  {
    category: "国家市场笔记",
    title: "墨西哥：市场研究起步清单",
    text: "这是待调研清单，不是已核实的市场结论。\n\n1. 目标车型与保有量结构是什么？\n2. 哪些企业经营制动产品批发？\n3. 买家有无进口能力或当地代理？\n4. 包装、语言、认证与清关有哪些要求？\n5. 交货到哪个港口或仓库？\n\n记录每项证据的来源与日期。法规、关税和认证应在交易前查询权威来源。",
  },
];
export const briefs = [
  {
    name: "焦作远川泵业",
    product: "工业离心泵",
    market: "墨西哥",
    detail:
      "一家模拟制造企业，主营用于工厂循环水系统的工业离心泵。计划寻找当地工业设备经销商。现有英文参数表，但没有经过验证的当地客户名单。",
    constraint:
      "预算有限，首轮交付 5 家有证据的潜客；项目周期 2 周。认证、出口经验与产品适用性待核实。",
  },
  {
    name: "中原制动科技",
    product: "汽车刹车片",
    market: "阿联酋",
    detail:
      "一家模拟制造企业，主营乘用车售后刹车片，具备自有品牌包装能力，希望寻找批量进口商。车型覆盖及测试报告需向工厂确认。",
    constraint:
      "首轮交付 5 家目标企业和开发邮件；项目周期 10 天。不承诺询盘或成交。",
  },
  {
    name: "豫新包装设备",
    product: "自动封箱机",
    market: "越南",
    detail:
      "一家模拟制造企业，为食品与日用品工厂提供封箱设备，拟寻找具备安装和售后能力的设备经销商。",
    constraint:
      "首轮优先研究 5 家渠道商；项目周期 2 周。电气适配、备件与售后边界待确认。",
  },
];
